name: APEX

config:
  double_q: false
  dueling: false
  noisy: false
  n_step: 3
  lr: .0001
  adam_epsilon: .00015
  buffer_size: 1000000
  prioritized_replay_alpha: 0.5
  final_prioritized_replay_beta: 1.0
  prioritized_replay_beta_annealing_timesteps: 2000000

  num_workers: 4
  num_envs_per_worker: 8
  rollout_fragment_length: 200
  train_batch_size: 512
  target_network_update_freq: 50000
  timesteps_per_iteration: 25000