name: PPO

config:
  num_workers: 1
  num_envs_per_worker: 1


  rollout_fragment_length: 16
  train_batch_size: 128
  num_sgd_iter: 3
  lr: 2e-4
  sgd_minibatch_size: 128
  batch_mode: "truncate_episodes"