name: PPO

config:
  num_workers: 2
  num_envs_per_worker: 1

  gamma: 0.983

  rollout_fragment_length: 200
  train_batch_size: 400
  num_sgd_iter: 1
  lr: 1e-4
  sgd_minibatch_size: 100
  batch_mode: "truncate_episodes"

  entropy_coeff: 1e-5
  lr_schedule: [
    [       0, 1e-4],
    [10000000, 5e-5],
    [80000000, 1e-5],
    [99000000, 1e-6],
  ]