name: PPO

config:
  num_workers: 4
  num_envs_per_worker: 1

  gamma: 0.997

  rollout_fragment_length: 500
  train_batch_size: 2000
  num_sgd_iter: 2
  lr: 1e-6
  sgd_minibatch_size: 500
  batch_mode: "truncate_episodes"

  entropy_coeff: 1e-5
  lr_schedule: [
    [       0, 1e-6],
    [10000000, 1e-6],
    [80000000, 2e-7],
    [99000000, 1e-8],
  ]