name: PPO

config:
  num_workers: 8
  num_envs_per_worker: 1

  gamma: 0.98

  rollout_fragment_length: 800
  train_batch_size: 6400
  num_sgd_iter: 3
  lr: 1e-4
  sgd_minibatch_size: 1600
  batch_mode: "truncate_episodes"

  entropy_coeff: 5e-5