name: PPO

config:
  num_workers: 10
  num_envs_per_worker: 1

  gamma: 0.997

  rollout_fragment_length: 800
  train_batch_size: 8000
  num_sgd_iter: 5
  lr: 5e-5
  sgd_minibatch_size: 800
  batch_mode: "truncate_episodes"

  entropy_coeff: 1e-5
  lr_schedule: [
    [       0, 5e-5],
    [10000000, 5e-5],
    [80000000, 1e-5],
    [99000000, 1e-6],
  ]