name: PPO

config:
  num_workers: 8
  num_envs_per_worker: 1

  gamma: 0.995

  rollout_fragment_length: 800
  train_batch_size: 6400
  num_sgd_iter: 1
  lr: 1e-5
  sgd_minibatch_size: 1600
  batch_mode: "truncate_episodes"

  entropy_coeff: 1e-5
  lr_schedule: [
    [       0, 1e-5],
    [10000000, 1e-5],
    [80000000, 2e-7],
    [99000000, 1e-8],
  ]