name: PPO

config:
  num_workers: 8
  num_envs_per_worker: 1

  gamma: 0.997

  rollout_fragment_length: 500
  train_batch_size: 4000
  num_sgd_iter: 1
  lr: 1e-4
  sgd_minibatch_size: 1000
  batch_mode: "truncate_episodes"

  entropy_coeff: 1e-5
  lr_schedule: [
    [       0, 1e-4],
    [10000000, 1e-5],
    [80000000, 2e-7],
    [99000000, 1e-8],
  ]