defaults:
  - algorithm: ppo
  - env: lux_ma_env
  - model: gnn_with_lstm
  - _self_

debug: false
verbose: 1

stop:
  timesteps_total: 1000000

checkpoint_at_end: true
checkpoint_freq: 30

local_dir: "~/ray_results"
# restore: <path to checkpoint>

metrics:
  log_replays: false # since they are broken

weights:
  win_rate_to_update: 0.6

wandb:
  entity: cerebro-ai  # under which account to find project
  project: luxai21
  group: opponent_testing  # this is just the group for the runs
  notes: testing multiple opponents with weight updating, larger latent, only 12x12 board size
  tags: [ GNN, Dev, Rllib ]
  mode: online
