defaults:
  - algorithm: ppo
  - env: lux_ma_env
  - model: v2
  - _self_

debug: false
verbose: 0

stop:
  timesteps_total: 4000000

checkpoint_at_end: true
checkpoint_freq: 15

local_dir: "~/ray_results"
# restore: <path to checkpoint>

metrics:
  log_replays: false # since they are broken

weights:
  win_rate_to_update: 0.65
  min_steps_between_updates: 5
  self_play: false # will only play against itself

wandb:
  entity: cerebro-ai  # under which account to find project
  project: luxai21
  group: alpha  # this is just the group for the runs
  notes: test run with large batch size and larger v2 model with simple obs
  tags: [ Dev, Rllib ]
  mode: online
