defaults:
  - algorithm: ppo
  - env: lux_ma_env
  - model: v2
  - _self_

debug: false
verbose: 1

stop:
  timesteps_total: 500000

checkpoint_at_end: true
checkpoint_freq: 30

local_dir: "~/ray_results"
# restore: <path to checkpoint>

metrics:
  log_replays: false # since they are broken

weights:
  win_rate_to_update: 0.5
  min_steps_betweeen_updates: 10
  self_play: false # will only play against itself

wandb:
  entity: cerebro-ai  # under which account to find project
  project: luxai21
  group: debug  # this is just the group for the runs
  notes: testing do nothing opponent
  tags: [ GNN, Dev, Rllib ]
  mode: online
