defaults:
  - algorithm: ppo
  - env: lux_ma_env
  - model: v2
  - _self_

debug: false
verbose: 1

stop:
  timesteps_total: 5000

checkpoint_at_end: true
checkpoint_freq: 30

local_dir: "~/ray_results"
# restore: <path to checkpoint>

metrics:
  log_replays: false # since they are broken

weights:
  win_rate_to_update: 0.7

wandb:
  entity: cerebro-ai  # under which account to find project
  project: luxai21
  group: debug  # this is just the group for the runs
  notes: testing new model v2 architecture
  tags: [ GNN, Dev, Rllib ]
  mode: online
