---
training:
  learning_rate: 0.001
  gamma: 0.995
  gae_lambda: 0.95
  batch_size: 64 # testing gradients
  step_count: 131072
  n_steps: 8192
  n_envs: 1  # Number of parallel environments to use in training

model:
  map_emb_dim: 128
  # TODO insert feature_extractor parameters
  net_arch_shared_layers: [128]
  net_arch_pi: [64, 32] # policy-function
  net_arch_vf: [128, 64, 32] # value-function